CREATE TABLE IF NOT EXISTS segment_id_generator (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    biz_type VARCHAR(64) NOT NULL UNIQUE,
    max_id BIGINT NOT NULL DEFAULT 0,
    step INT NOT NULL DEFAULT 1000,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);